In [15]:
from fpl_selector.data.collectors import VastaavCollector, FPLAPICollector, CollectorConfig
from fpl_selector.data.storage import DataStorage
from fpl_selector.features.engineering import FeatureEngineer
from fpl_selector.models.predictor import PointsPredictor
import polars as pl

Explore the data collected in DataStorage

In [16]:
storage = DataStorage()

In [17]:
collector = VastaavCollector()
fpl_coll = FPLAPICollector()
# collector.collect()
# df = await collector.collect('2025-26')
# df.head()

Create and store features for model training

In [18]:
import pathlib


print(storage.get_data_freshness())
gws = storage.load_gameweeks()

feature_eng = FeatureEngineer()
features = feature_eng.transform(gws)

features = storage.load_features()
# players = storage.load_players()
numeric_df = features.select(pl.selectors.numeric())
features.head()

{'players': datetime.datetime(2026, 2, 1, 20, 1, 17, 454239), 'fixtures': datetime.datetime(2026, 2, 1, 20, 1, 17, 695136), 'gameweeks': datetime.datetime(2026, 2, 1, 20, 1, 18, 766521)}

shape: (5, 89)
┌────────┬──────────┬───────────┬─────┬───┬──────────────┬──────────────┬────────────┬─────────────┐
│ name   ┆ position ┆ team      ┆ xP  ┆ … ┆ points_per_m ┆ value_change ┆ team_goals ┆ opponent_st │
│ ---    ┆ ---      ┆ ---       ┆ --- ┆   ┆ illion       ┆ ---          ┆ ---        ┆ r           │
│ str    ┆ str      ┆ str       ┆ f32 ┆   ┆ ---          ┆ f64          ┆ i64        ┆ ---         │
│        ┆          ┆           ┆     ┆   ┆ f64          ┆              ┆            ┆ str         │
╞════════╪══════════╪═══════════╪═════╪═══╪══════════════╪══════════════╪════════════╪═════════════╡
│ Aaron  ┆ DEF      ┆ Brentford ┆ 1.0 ┆ … ┆ 0.0          ┆ null         ┆ 1          ┆ 16          │
│ Hickey ┆          ┆           ┆     ┆   ┆              ┆              ┆            ┆             │
│ Aaron  ┆ DEF      ┆ Brentford ┆ 0.5 ┆ … ┆ 2.5          ┆ 0.0          ┆ 1          ┆ 2           │
│ Hickey ┆          ┆           ┆     ┆   ┆              ┆              ┆            ┆             │
│ Aaron  ┆ DEF      ┆ Brentford ┆ 0.8 ┆ … ┆ 0.0          ┆ 0.0          ┆ 1          ┆ 17          │
│ Hickey ┆          ┆           ┆     ┆   ┆              ┆              ┆            ┆             │
│ Aaron  ┆ DEF      ┆ Brentford ┆ 0.2 ┆ … ┆ 2.5          ┆ 0.0          ┆ 2          ┆ 7           │
│ Hickey ┆          ┆           ┆     ┆   ┆              ┆              ┆            ┆             │
│ Aaron  ┆ DEF      ┆ Brentford ┆ 0.3 ┆ … ┆ 0.0          ┆ 0.0          ┆ 1          ┆ 10          │
│ Hickey ┆          ┆           ┆     ┆   ┆              ┆              ┆            ┆             │
└────────┴──────────┴───────────┴─────┴───┴──────────────┴──────────────┴────────────┴─────────────┘

In [19]:
storage.load_teams()

shape: (20, 21)
┌──────┬──────┬──────┬─────┬───┬──────────────────┬──────────────────┬──────────────────┬──────────┐
│ code ┆ draw ┆ form ┆ id  ┆ … ┆ strength_attack_ ┆ strength_defence ┆ strength_defence ┆ pulse_id │
│ ---  ┆ ---  ┆ ---  ┆ --- ┆   ┆ away             ┆ _home            ┆ _away            ┆ ---      │
│ i64  ┆ i64  ┆ str  ┆ i64 ┆   ┆ ---              ┆ ---              ┆ ---              ┆ i64      │
│      ┆      ┆      ┆     ┆   ┆ i64              ┆ i64              ┆ i64              ┆          │
╞══════╪══════╪══════╪═════╪═══╪══════════════════╪══════════════════╪══════════════════╪══════════╡
│ 3    ┆ 0    ┆ null ┆ 1   ┆ … ┆ 1400             ┆ 1260             ┆ 1350             ┆ 1        │
│ 7    ┆ 0    ┆ null ┆ 2   ┆ … ┆ 1170             ┆ 1140             ┆ 1200             ┆ 2        │
│ 90   ┆ 0    ┆ null ┆ 3   ┆ … ┆ 1090             ┆ 1100             ┆ 1100             ┆ 43       │
│ 91   ┆ 0    ┆ null ┆ 4   ┆ … ┆ 1240             ┆ 1200             ┆ 1200             ┆ 127      │
│ 94   ┆ 0    ┆ null ┆ 5   ┆ … ┆ 1110             ┆ 1170             ┆ 1240             ┆ 130      │
│ …    ┆ …    ┆ …    ┆ …   ┆ … ┆ …                ┆ …                ┆ …                ┆ …        │
│ 17   ┆ 0    ┆ null ┆ 16  ┆ … ┆ 1110             ┆ 1100             ┆ 1150             ┆ 15       │
│ 56   ┆ 0    ┆ null ┆ 17  ┆ … ┆ 1120             ┆ 1100             ┆ 1170             ┆ 29       │
│ 6    ┆ 0    ┆ null ┆ 18  ┆ … ┆ 1150             ┆ 1200             ┆ 1200             ┆ 21       │
│ 21   ┆ 0    ┆ null ┆ 19  ┆ … ┆ 1050             ┆ 1100             ┆ 1100             ┆ 25       │
│ 39   ┆ 0    ┆ null ┆ 20  ┆ … ┆ 1050             ┆ 1090             ┆ 1120             ┆ 38       │
└──────┴──────┴──────┴─────┴───┴──────────────────┴──────────────────┴──────────────────┴──────────┘

In [20]:
opp_ids = features.join(storage.load_teams().select(["id", "name"]),
		left_on="opponent_team", right_on="id", how='left'
)
# opp_ids = opp_ids.rename({"id": "opp_team_id"})

opp_ids

shape: (5_821, 90)
┌─────────────┬──────────┬───────────┬─────┬───┬────────────┬────────────┬────────────┬────────────┐
│ name        ┆ position ┆ team      ┆ xP  ┆ … ┆ value_chan ┆ team_goals ┆ opponent_s ┆ name_right │
│ ---         ┆ ---      ┆ ---       ┆ --- ┆   ┆ ge         ┆ ---        ┆ tr         ┆ ---        │
│ str         ┆ str      ┆ str       ┆ f32 ┆   ┆ ---        ┆ i64        ┆ ---        ┆ str        │
│             ┆          ┆           ┆     ┆   ┆ f64        ┆            ┆ str        ┆            │
╞═════════════╪══════════╪═══════════╪═════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Aaron       ┆ DEF      ┆ Brentford ┆ 1.0 ┆ … ┆ null       ┆ 1          ┆ 16         ┆ Nott'm     │
│ Hickey      ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆ Forest     │
│ Aaron       ┆ DEF      ┆ Brentford ┆ 0.5 ┆ … ┆ 0.0        ┆ 1          ┆ 2          ┆ Aston      │
│ Hickey      ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆ Villa      │
│ Aaron       ┆ DEF      ┆ Brentford ┆ 0.8 ┆ … ┆ 0.0        ┆ 1          ┆ 17         ┆ Sunderland │
│ Hickey      ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ Aaron       ┆ DEF      ┆ Brentford ┆ 0.2 ┆ … ┆ 0.0        ┆ 2          ┆ 7          ┆ Chelsea    │
│ Hickey      ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ Aaron       ┆ DEF      ┆ Brentford ┆ 0.3 ┆ … ┆ 0.0        ┆ 1          ┆ 10         ┆ Fulham     │
│ Hickey      ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …        ┆ …         ┆ …   ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ İlkay       ┆ MID      ┆ Man City  ┆ 0.0 ┆ … ┆ 0.0        ┆ 3          ┆ 14         ┆ Man Utd    │
│ Gündoğan    ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ İlkay       ┆ MID      ┆ Man City  ┆ 0.0 ┆ … ┆ 0.0        ┆ 1          ┆ 1          ┆ Arsenal    │
│ Gündoğan    ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ İlkay       ┆ MID      ┆ Man City  ┆ 0.0 ┆ … ┆ 0.0        ┆ 3          ┆ 3          ┆ Burnley    │
│ Gündoğan    ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ İlkay       ┆ MID      ┆ Man City  ┆ 0.0 ┆ … ┆ 0.0        ┆ 2          ┆ 9          ┆ Everton    │
│ Gündoğan    ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆            │
│ İlkay       ┆ MID      ┆ Man City  ┆ 0.0 ┆ … ┆ 0.0        ┆ 0          ┆ 2          ┆ Aston      │
│ Gündoğan    ┆          ┆           ┆     ┆   ┆            ┆            ┆            ┆ Villa      │
└─────────────┴──────────┴───────────┴─────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
storage.load_teams().head()

shape: (5, 21)
┌──────┬──────┬──────┬─────┬───┬──────────────────┬──────────────────┬──────────────────┬──────────┐
│ code ┆ draw ┆ form ┆ id  ┆ … ┆ strength_attack_ ┆ strength_defence ┆ strength_defence ┆ pulse_id │
│ ---  ┆ ---  ┆ ---  ┆ --- ┆   ┆ away             ┆ _home            ┆ _away            ┆ ---      │
│ i64  ┆ i64  ┆ str  ┆ i64 ┆   ┆ ---              ┆ ---              ┆ ---              ┆ i64      │
│      ┆      ┆      ┆     ┆   ┆ i64              ┆ i64              ┆ i64              ┆          │
╞══════╪══════╪══════╪═════╪═══╪══════════════════╪══════════════════╪══════════════════╪══════════╡
│ 3    ┆ 0    ┆ null ┆ 1   ┆ … ┆ 1400             ┆ 1260             ┆ 1350             ┆ 1        │
│ 7    ┆ 0    ┆ null ┆ 2   ┆ … ┆ 1170             ┆ 1140             ┆ 1200             ┆ 2        │
│ 90   ┆ 0    ┆ null ┆ 3   ┆ … ┆ 1090             ┆ 1100             ┆ 1100             ┆ 43       │
│ 91   ┆ 0    ┆ null ┆ 4   ┆ … ┆ 1240             ┆ 1200             ┆ 1200             ┆ 127      │
│ 94   ┆ 0    ┆ null ┆ 5   ┆ … ┆ 1110             ┆ 1170             ┆ 1240             ┆ 130      │
└──────┴──────┴──────┴─────┴───┴──────────────────┴──────────────────┴──────────────────┴──────────┘

In [6]:
fpl_data = await fpl_coll.get_live_gameweek_data(25)

In [7]:
fpl_fts = set(fpl_data.columns)
gws_fts = set(gws.columns)

list(gws_fts - fpl_fts)

['modified',
 'opponent_team',
 'round',
 'xP',
 'element',
 'team_h_score',
 'was_home',
 'team_a_score',
 'fixture',
 'season',
 'kickoff_time']

In [9]:
fixture_data = await fpl_coll.get_fixtures(25)

In [ ]:
fix1 = fixture_data.select('stats')[0]
fix1

'{"columns":[{"Scalar":{"name":"stats","unit_series":[255,255,255,255,88,3,0,0,4,0,0,0,242,255,255,255,20,0,0,0,4,0,1,0,0,0,10,0,11,0,8,0,10,0,4,0,242,255,255,255,72,0,0,0,16,0,0,0,0,0,10,0,12,0,0,0,4,0,8,0,1,0,0,0,4,0,0,0,244,255,255,255,24,0,0,0,12,0,0,0,8,0,12,0,4,0,8,0,1,0,0,0,52,0,0,0,9,0,0,0,95,80,76,95,70,76,65,71,83,0,0,0,1,0,0,0,4,0,0,0,236,255,255,255,216,2,0,0,204,2,0,0,24,0,0,0,1,21,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,1,0,0,0,4,0,0,0,236,255,255,255,152,2,0,0,140,2,0,0,24,0,0,0,1,13,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,3,0,0,0,44,2,0,0,24,1,0,0,4,0,0,0,236,255,255,255,4,1,0,0,248,0,0,0,24,0,0,0,1,21,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,1,0,0,0,4,0,0,0,236,255,255,255,196,0,0,0,184,0,0,0,24,0,0,0,1,13,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,2,0,0,0,80,0,0,0,4,0,0,0,236,255,255,255,56,0,0,0,32,0,0,0,24,0,0,0,1,2,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,0,0,0,0,244,255,255,255,64,0,0,0,1,0,0,0,8,0,9,0,4,0,8,0,7,0,0,0,101,108,101,109,101,110,116,0,236,255,255,255,56,0,0,0,32,0,0,0,24,0,0,0,1,2,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,0,0,0,0,244,255,255,255,64,0,0,0,1,0,0,0,8,0,9,0,4,0,8,0,5,0,0,0,118,97,108,117,101,0,0,0,252,255,255,255,4,0,4,0,4,0,0,0,105,116,101,109,0,0,0,0,252,255,255,255,4,0,4,0,1,0,0,0,104,0,0,0,236,255,255,255,4,1,0,0,248,0,0,0,24,0,0,0,1,21,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,1,0,0,0,4,0,0,0,236,255,255,255,196,0,0,0,184,0,0,0,24,0,0,0,1,13,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,2,0,0,0,80,0,0,0,4,0,0,0,236,255,255,255,56,0,0,0,32,0,0,0,24,0,0,0,1,2,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,0,0,0,0,244,255,255,255,64,0,0,0,1,0,0,0,8,0,9,0,4,0,8,0,7,0,0,0,101,108,101,109,101,110,116,0,236,255,255,255,56,0,0,0,32,0,0,0,24,0,0,0,1,2,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,0,0,0,0,244,255,255,255,64,0,0,0,1,0,0,0,8,0,9,0,4,0,8,0,5,0,0,0,118,97,108,117,101,0,0,0,252,255,255,255,4,0,4,0,4,0,0,0,105,116,101,109,0,0,0,0,252,255,255,255,4,0,4,0,1,0,0,0,97,0,0,0,236,255,255,255,44,0,0,0,32,0,0,0,24,0,0,0,1,24,0,0,16,0,18,0,4,0,16,0,17,0,8,0,0,0,12,0,0,0,0,0,252,255,255,255,4,0,4,0,10,0,0,0,105,100,101,110,116,105,102,105,101,114,0,0,252,255,255,255,4,0,4,0,4,0,0,0,105,116,101,109,0,0,0,0,252,255,255,255,4,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255,104,2,0,0,4,0,0,0,236,255,255,255,192,3,0,0,0,0,0,0,20,0,0,0,4,0,3,0,12,0,19,0,16,0,18,0,12,0,4,0,226,255,255,255,1,0,0,0,0,0,0,0,128,1,0,0,52,0,0,0,36,0,0,0,20,0,0,0,0,0,14,0,28,0,4,0,12,0,16,0,20,0,24,0,1,0,0,0,1,0,0,0,0,0,0,0,250,255,255,255,1,0,6,0,5,0,4,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,125,0,0,0,0,0,0,0,192,0,0,0,0,0,0,0,74,0,0,0,0,0,0,0,64,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,1,0,0,0,0,0,0,51,0,0,0,0,0,0,0,128,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,1,0,0,0,0,0,0,115,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,126,0,0,0,0,0,0,0,128,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,2,0,0,0,0,0,0,54,0,0,0,0,0,0,0,192,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,192,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,192,2,0,0,0,0,0,0,107,0,0,0,0,0,0,0,64,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,3,0,0,0,0,0,0,120,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,0,0,0,0,0,0,0,40,181,47,253,0,88,129,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,176,0,0,0,0,0,0,0,40,181,47,253,0,88,101,3,0,210,134,19,25,144,57,173,1,160,89,68,129,210,0,190,149,109,251,153,153,25,139,120,84,135,134,139,74,1,47,216,193,212,9,55,128,5,179,12,198,72,247,192,149,57,63,78,57,73,65,207,90,22,107,28,121,50,120,98,172,121,114,196,60,235,199,83,92,226,46,93,160,204,89,202,161,91,210,66,28,9,11,0,32,96,80,116,32,48,64,114,102,132,16,15,63,204,49,102,90,6,234,252,81,205,89,129,19,0,0,0,18,2,0,0,0,0,0,0,40,181,47,253,0,88,205,1,0,180,2,112,101,110,97,108,116,105,101,115,95,115,97,118,101,100,109,105,115,115,101,100,100,101,102,101,110,115,105,118,101,95,99,111,110,116,114,105,98,117,116,105,111,110,3,0,208,88,41,64,82,208,17,120,214,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,96,0,0,0,0,0,0,0,40,181,47,253,0,88,21,1,0,136,0,0,1,0,2,0,3,4,20,32,0,0,0,0,0,0,0,7,0,32,19,208,29,232,120,5,88,128,49,24,120,0,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,40,181,47,253,0,88,21,3,0,148,2,1,0,1,0,2,27,20,16,12,10,8,7,6,5,3,1,254,255,253,255,252,255,13,0,11,0,7,6,5,3,3,2,1,1,0,0,0,0,0,0,0,28,0,160,11,200,7,50,3,89,64,62,144,25,100,153,3,1,96,96,48,48,24,24,12,140,27,8,50,3,153,128,122,192,49,224,4,184,3,142,1,39,192,29,112,12,56,1,238,86,94,0,24,15,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,40,181,47,253,0,88,109,3,0,180,2,37,3,0,181,2,0,9,144,1,37,3,5,3,2,7,2,157,2,4,255,1,10,14,46,3,251,1,249,1,1,5,9,157,4,14,181,2,0,0,0,0,0,0,31,0,32,11,228,91,25,18,32,31,144,24,24,2,91,17,88,138,0,228,91,2,9,144,15,100,6,70,131,209,107,32,22,12,4,153,129,44,192,64,144,25,24,13,140,158,138,88,48,16,100,30,138,88,48,48,24,184,146,12,52,39,0,55,0,0,96,0,0,0,0,0,0,0,40,181,47,253,0,88,45,1,0,144,0,0,3,0,5,0,6,7,10,24,35,0,0,0,0,0,0,0,8,0,32,11,200,7,50,6,58,89,1,0,96,12,6,30,0,22,0,0,0,0,0,0,0,0,0,0,24,1,0,0,0,0,0,0,40,181,47,253,0,88,213,2,0,68,2,1,0,1,0,2,1,5,3,2,1,45,34,29,28,20,17,14,13,12,3,1,15,10,9,8,7,6,4,1,0,0,0,0,0,0,0,27,0,32,11,200,14,212,12,116,1,249,64,102,32,11,200,14,116,6,178,128,236,64,103,32,11,200,14,116,6,178,128,124,32,51,144,5,228,3,153,129,76,64,63,144,121,133,88,48,240,0,176,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,1,0,0,0,0,0,0,40,181,47,253,0,88,61,3,0,244,2,86,1,0,179,2,0,186,100,1,194,2,186,85,1,100,179,100,86,186,91,87,1,92,1,94,98,1,89,1,97,237,1,87,92,94,91,100,86,98,97,1,0,0,0,0,0,0,32,32,192,147,164,3,171,132,96,65,32,159,204,178,228,203,108,150,124,7,102,102,180,209,178,24,216,192,144,121,33,38,179,145,201,34,200,71,51,143,196,50,27,45,139,3,135,129,75,166,57,1,184,1,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0],"length":1}}]}'

In [5]:
teams = storage.load_teams()

In [ ]:
list(zip(numeric_df.columns,numeric_df.dtypes))

[('xP', Float32),
 ('assists', Int8),
 ('bonus', Int8),
 ('bps', Int8),
 ('clean_sheets', Int8),
 ('clearances_blocks_interceptions', Int8),
 ('creativity', Float32),
 ('defensive_contribution', Int8),
 ('element', Int16),
 ('expected_assists', Float32),
 ('expected_goal_involvements', Float32),
 ('expected_goals', Float32),
 ('expected_goals_conceded', Float32),
 ('fixture', Int8),
 ('goals_conceded', Int8),
 ('goals_scored', Int8),
 ('ict_index', Float32),
 ('influence', Float32),
 ('minutes', Int8),
 ('opponent_team', Int8),
 ('own_goals', Int8),
 ('penalties_missed', Int8),
 ('penalties_saved', Int8),
 ('recoveries', Int8),
 ('red_cards', Int8),
 ('round', Int8),
 ('saves', Int8),
 ('selected', Int32),
 ('starts', Int8),
 ('tackles', Int8),
 ('team_a_score', Int8),
 ('team_h_score', Int8),
 ('threat', Float32),
 ('total_points', Int8),
 ('transfers_balance', Int32),
 ('transfers_in', Int32),
 ('transfers_out', Int32),
 ('value', Float64),
 ('yellow_cards', Int8),
 ('GW', Int8),
 ('total_points_roll_3', Float64),
 ('minutes_roll_3', Float64),
 ('goals_scored_roll_3', Float64),
 ('assists_roll_3', Float64),
 ('clean_sheets_roll_3', Float64),
 ('expected_goals_roll_3', Float32),
 ('expected_assists_roll_3', Float32),
 ('expected_goal_involvements_roll_3', Float32),
 ('bps_roll_3', Float64),
 ('influence_roll_3', Float32),
 ('creativity_roll_3', Float32),
 ('threat_roll_3', Float32),
 ('total_points_roll_5', Float64),
 ('minutes_roll_5', Float64),
 ('goals_scored_roll_5', Float64),
 ('assists_roll_5', Float64),
 ('clean_sheets_roll_5', Float64),
 ('expected_goals_roll_5', Float32),
 ('expected_assists_roll_5', Float32),
 ('expected_goal_involvements_roll_5', Float32),
 ('bps_roll_5', Float64),
 ('influence_roll_5', Float32),
 ('creativity_roll_5', Float32),
 ('threat_roll_5', Float32),
 ('total_points_roll_10', Float64),
 ('minutes_roll_10', Float64),
 ('goals_scored_roll_10', Float64),
 ('assists_roll_10', Float64),
 ('clean_sheets_roll_10', Float64),
 ('expected_goals_roll_10', Float32),
 ('expected_assists_roll_10', Float32),
 ('expected_goal_involvements_roll_10', Float32),
 ('bps_roll_10', Float64),
 ('influence_roll_10', Float32),
 ('creativity_roll_10', Float32),
 ('threat_roll_10', Float32),
 ('form_trend', Float64),
 ('points_per_90', Float64),
 ('points_per_million', Float64),
 ('value_change', Float64),
 ('team_goals', Int64)]

In [10]:
new_df = numeric_df.with_columns(
	pl.col(pl.Int64, pl.Float64).shrink_dtype()
)
lst = list(zip(new_df.columns, new_df.dtypes))
lst[::-1]

[('team_goals', Int8),
 ('value_change', Float32),
 ('points_per_million', Float32),
 ('points_per_90', Float32),
 ('form_trend', Float32),
 ('threat_roll_10', Float32),
 ('creativity_roll_10', Float32),
 ('influence_roll_10', Float32),
 ('bps_roll_10', Float32),
 ('expected_goal_involvements_roll_10', Float32),
 ('expected_assists_roll_10', Float32),
 ('expected_goals_roll_10', Float32),
 ('clean_sheets_roll_10', Float32),
 ('assists_roll_10', Float32),
 ('goals_scored_roll_10', Float32),
 ('minutes_roll_10', Float32),
 ('total_points_roll_10', Float32),
 ('threat_roll_5', Float32),
 ('creativity_roll_5', Float32),
 ('influence_roll_5', Float32),
 ('bps_roll_5', Float32),
 ('expected_goal_involvements_roll_5', Float32),
 ('expected_assists_roll_5', Float32),
 ('expected_goals_roll_5', Float32),
 ('clean_sheets_roll_5', Float32),
 ('assists_roll_5', Float32),
 ('goals_scored_roll_5', Float32),
 ('minutes_roll_5', Float32),
 ('total_points_roll_5', Float32),
 ('threat_roll_3', Float32),
 ('creativity_roll_3', Float32),
 ('influence_roll_3', Float32),
 ('bps_roll_3', Float32),
 ('expected_goal_involvements_roll_3', Float32),
 ('expected_assists_roll_3', Float32),
 ('expected_goals_roll_3', Float32),
 ('clean_sheets_roll_3', Float32),
 ('assists_roll_3', Float32),
 ('goals_scored_roll_3', Float32),
 ('minutes_roll_3', Float32),
 ('total_points_roll_3', Float32),
 ('GW', Int8),
 ('yellow_cards', Int8),
 ('value', Float32),
 ('transfers_out', Int32),
 ('transfers_in', Int32),
 ('transfers_balance', Int32),
 ('total_points', Int8),
 ('threat', Float32),
 ('team_h_score', Int8),
 ('team_a_score', Int8),
 ('tackles', Int8),
 ('starts', Int8),
 ('selected', Int32),
 ('saves', Int8),
 ('round', Int8),
 ('red_cards', Int8),
 ('recoveries', Int8),
 ('penalties_saved', Int8),
 ('penalties_missed', Int8),
 ('own_goals', Int8),
 ('opponent_team', Int8),
 ('minutes', Int8),
 ('influence', Float32),
 ('ict_index', Float32),
 ('goals_scored', Int8),
 ('goals_conceded', Int8),
 ('fixture', Int8),
 ('expected_goals_conceded', Float32),
 ('expected_goals', Float32),
 ('expected_goal_involvements', Float32),
 ('expected_assists', Float32),
 ('element', Int16),
 ('defensive_contribution', Int8),
 ('creativity', Float32),
 ('clearances_blocks_interceptions', Int8),
 ('clean_sheets', Int8),
 ('bps', Int8),
 ('bonus', Int8),
 ('assists', Int8),
 ('xP', Float32)]

Train models

In [ ]:
predictor = PointsPredictor('./')
predictor.train(features)
# predictor.save()

FWD
Index(['minutes_roll_5', 'total_points_roll_3', 'total_points_roll_5',
       'goals_scored_roll_5', 'assists_roll_5', 'expected_goals_roll_5',
       'expected_goal_involvements_roll_5', 'bps_roll_5', 'threat_roll_5',
       'form_trend', 'points_per_90', 'points_per_million'],
      dtype='object')
X_Train
     minutes_roll_5  total_points_roll_3  total_points_roll_5  \
0          0.000000             0.000000             0.000000
1          0.000000             0.000000             0.000000
2          0.000000             0.000000             0.000000
3          0.000000             0.000000             0.000000
4          0.000000             0.000000             0.000000
..              ...                  ...                  ...
500       47.000000             3.500000             3.500000
501       50.666667             2.666667             2.666667
502       58.750000             1.000000             2.500000
503       62.800000             2.666667             3.000000
504       58.000000             2.333333             1.600000

     goals_scored_roll_5  assists_roll_5  expected_goals_roll_5  \
0               0.000000             0.0               0.000000
1               0.000000             0.0               0.000000
2               0.000000             0.0               0.000000
3               0.000000             0.0               0.000000
4               0.000000             0.0               0.000000
..                   ...             ...                    ...
500             0.500000             0.0               0.260000
501             0.333333             0.0               0.186667
502             0.250000             0.0               0.185000
503             0.200000             0.2               0.172000
504             0.000000             0.2               0.142000

     expected_goal_involvements_roll_5  bps_roll_5  threat_roll_5  form_trend  \
0                             0.000000        0.00       0.000000    0.000000
1                             0.000000        0.00       0.000000    0.000000
2                             0.000000        0.00       0.000000    0.000000
3                             0.000000        0.00       0.000000    0.000000
4                             0.000000        0.00       0.000000    0.000000
..                                 ...         ...            ...         ...
500                           0.260000       11.00      28.500000    0.000000
501                           0.186667        7.00      20.333334    0.000000
502                           0.187500        6.25      20.500000   -1.500000
503                           0.174000        7.60      20.600000   -0.333333
504                           0.144000        2.60      14.000000   -0.166667

     points_per_90  points_per_million
0         0.000000            0.000000
1         0.000000            0.000000
2         0.000000            0.000000
3         0.000000            0.000000
4         0.000000            0.000000
..             ...                 ...
500       0.000000            0.000000
501       1.551724            1.818182
502       2.168675            3.636364
503       5.696203            9.090909
504       0.000000            0.000000

[505 rows x 12 columns]

PosixPath('models.joblib')